[package]
name = "codesweeper-ui"
version = "0.1.0"
authors = ["Warren Galyen <wgalyen@bellhelmets.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.6.0"

[dependencies.codesweeper-lib]
path = "../codesweeper-lib"
version = "*"